Prototype  sensitive terms metric
UNLSiteMaster/metric_sensitive_terms pull request #1
Opened 2020-09-15 18:16 UTC by jsturek

2020-09-16 13:46 UTC, jsturek commented on src/Metric.php
> +            'See [the WDN style guide documentation](https://wdn.unl.edu/unl-web-framework-5-standards-guide) for help on this topic.',
Need to identify or create help page how to handle sensitive terms.

2021-03-04 19:58 UTC, skoolbus39 requested changes, later dismissed

2021-03-04 19:58 UTC, skoolbus39 commented on src/Metric.php
> +}
No newline at end of file

2021-03-04 19:58 UTC, skoolbus39 commented on src/Plugin.php
> +}
No newline at end of file

2021-03-04 19:58 UTC, skoolbus39 commented on src/terms_list/.gitignore
> +!.gitignore
No newline at end of file

2021-03-04 19:58 UTC, skoolbus39 commented on src/terms_list/default.csv
> +you guys, these guys, my guys, those guys, hey guys, hi guys, the guys, these guys, thanks guys, guys?
No newline at end of file

2021-03-04 19:58 UTC, skoolbus39 commented on tests/MetricTest.php
> +}
No newline at end of file

2021-03-04 19:58 UTC, skoolbus39 commented on tests/data/sensitive_terms.html
> +</html>
No newline at end of file

2021-03-31 20:08 UTC, merged